---
version: '3'

volumes:
# TODO add named volumes
  db:
  wordpress:

services:

  reverse-proxy-nginx:
    container_name: nginx
    # TODO configure nginx
    # image: nginx:1.20.1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - default
    restart: always

  wordpress:
    container_name: wordpress
    # TODO configure wordpress
    image: wordpress:5.7.2-apache
    volumes:
      - wordpress:/var/www/html
    networks:
      - default
    environment:
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpressdb
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    # TODO configure mysql
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpressdb
    restart: always
  
networks:
  default: